[Listen]
# 1081 = DEFAULT, SOCKS4, SOCKS5, HTTP
# 1080 = DEFAULT, SOCKS4, SOCKS5, HTTP

[Tun]
198.18.0.1/24 = DEFAULT

[Fake DNS]
INET4 = 198.18.0.1/24
INET6 = 2001:2::/48
LEASE-TIME = 60

[External]
EEVPN=https://api.eeox.net/api/v1/client/subscribe?token=f09488ddab931bf666e9bf2e1a8638ba

[Proxy]
VPN-AGENT-NODE = ws://127.0.0.1:2345/tunnel/eca-iosp-order-manager%40prod#TUNNEL
VPN-HK-PROXY-NODE = http://10.15.9.57:808
# VPN-ENDPOINT-NODE = ws://192.168.1.201:2345/tunnel/BZ#TUNNEL
VPN-ENDPOINT-NODE = ws://139.196.84.154:2345/tunnel/BZ#TUNNEL
JDYD-NODE = ws://139.196.84.154:2345/tunnel/octopus-eai-jd@prod#JDYD-NODE
EG-CONNECT-NODE = ws://139.196.84.154:2345/tunnel/EG-CONNECT#EG-CONNECT

[Proxy Group]
# VPN local network
# VPN-ENDPOINT = select,DIRECT
# VPN-TO-HK = chain,VPN-HK-PROXY-NODE
# VPN-TO-INNER = chain,VPN-AGENT-NODE

# VPN remote network
VPN-ENDPOINT = select,VPN-ENDPOINT-NODE
VPN-TO-HK = chain,VPN-ENDPOINT-NODE,VPN-HK-PROXY-NODE
VPN-TO-INNER = chain,VPN-ENDPOINT-NODE,VPN-AGENT-NODE

JDYD = chain,JDYD-NODE
# CLAUDE = select,EG-CONNECT-NODE
CLAUDE = select,日本 04E0

[Rule]
# RULE-SET,rule.d/video.list,国外流量
# RULE-SET,rule.d/tiktok.list,一元机场
# RULE-SET,rule.d/facebook.list,一元机场
# RULE-SET,rule.d/twitter.list,一元机场
# RULE-SET,rule.d/openai.list,VPN-CHAIN
# RULE-SET,rule.d/dropbox.list,VPN-TO-HK
RULE-SET,rule.d/google.list,VPN-TO-HK
RULE-SET,rule.d/github.list,VPN-TO-HK

# RULE-SET,rule.d/cn.list,DIRECT

# VPN network
RULE-SET,rule.d/vpn/vpn.local.list,VPN-TO-INNER
RULE-SET,rule.d/vpn/vpn.remote.list,VPN-ENDPOINT

RULE-SET,rule.d/vpn/vpn.jdyd.list,JDYD

# check: https://scamalytics.com/
DOMAIN-SUFFIX,ip111.cn,CLAUDE
RULE-SET,rule.d/claude.list,CLAUDE

DOMAIN-SUFFIX,gitee.com,JDYD
DOMAIN-SUFFIX,github-cn.kering.cloud,DIRECT
