# Proxies
# TUNNEL = ws://127.0.0.1:2345/tunnel?agent=BZ#TUNNEL
TUNNEL = ws://192.168.1.201:2345/tunnel?agent=BZ#TUNNEL
# TUNNEL = ws://180.156.53.116:2345/tunnel?agent=BZ#TUNNEL

GROUP = subscribe:https://sub3.smallstrawberry.com/api/v1/client/subscribe?token=1ab79cc4b202d916cdc8e375c7b03266
