# Proxies
# TUNNEL = ws://127.0.0.1:2345/tunnel?agent=BZ#TUNNEL
TUNNEL = ws://192.168.1.201:2345/tunnel?agent=BZ#TUNNEL
# TUNNEL = ws://61.172.218.39:2345/tunnel?agent=BZ#TUNNEL
TUNNEL-NEXT-HOP = http://10.15.9.57:808
MOEHOT = ssh://root:Aimon2015Aliyun!123@139.196.84.154

GROUP = subscribe:https://sub3.smallstrawberry.com/api/v1/client/subscribe?token=1ab79cc4b202d916cdc8e375c7b03266
