# 转发规则

RULE-SET,rule.d/video.list,一元机场
RULE-SET,rule.d/tiktok.list,一元机场

RULE-SET,rule.d/twitter.list,一元机场
RULE-SET,rule.d/facebook.list,一元机场
RULE-SET,rule.d/twitter.list,一元机场

RULE-SET,rule.d/openai.list,一元机场
RULE-SET,rule.d/google.list,一元机场
RULE-SET,rule.d/github.list,一元机场
RULE-SET,rule.d/dropbox.list,一元机场

# RULE-SET,rule.d/cn.list,DIRECT

RULE-SET,rule.d/vpn/vpn.local.list,TUNNEL
# RULE-SET,rule.d/vpn/vpn.remote.list,TUNNEL
