[Listen]
1081 = DEFAULT, SOCKS4, SOCKS5, HTTP
1082 = 国外流量, SOCKS4, SOCKS5, HTTP

[External]
# 一元机场 = https://sub3.smallstrawberry.com/api/v1/client/subscribe?token=1ab79cc4b202d916cdc8e375c7b03266
国外流量 = http://fbapiv2.fbsublink.com/flydsubal/qcexzkf6b6w2ziwl?clash=1&extend=1

[Proxy]
# Proxies
# TUNNEL = ws://127.0.0.1:2345/tunnel?agent=eca-iosp-order-manager%40prod#TUNNEL
TUNNEL = ws://192.168.1.201:2345/tunnel?agent=BZ#TUNNEL
TUNNEL-DIRECT-HOP = http://10.15.9.57:808
MOEHOT = ssh://aimon:Aimon2015Aliyun!123@139.224.238.197:22

[Proxy Group]
TUNNEL-NEXT-HOP-CHAIN = chain,TUNNEL,TUNNEL-DIRECT-HOP

[Rule]
# 转发规则

# RULE-SET,rule.d/video.list,一元机场
# RULE-SET,rule.d/tiktok.list,一元机场

# RULE-SET,rule.d/twitter.list,一元机场
# RULE-SET,rule.d/facebook.list,一元机场
# RULE-SET,rule.d/twitter.list,一元机场

# RULE-SET,rule.d/openai.list,TUNNEL-NEXT-HOP
# RULE-SET,rule.d/google.list,TUNNEL-NEXT-HOP
# RULE-SET,rule.d/github.list,TUNNEL-NEXT-HOP
# RULE-SET,rule.d/dropbox.list,TUNNEL-NEXT-HOP

# RULE-SET,rule.d/cn.list,DIRECT

# RULE-SET,rule.d/vpn/vpn.local.list,TUNNEL
RULE-SET,rule.d/vpn/vpn.remote.list,TUNNEL
RULE-SET,rule.d/vpn/moehot.list,MOEHOT
